### ISSUE TITLE
Specify conda channel

### ISSUE THREAD

**Issue by w14** [JoshEngels/MultiDimensionalFeatures#2]
This command:

```bash
conda create --name multid_features --file requirements.txt
```

Doesn't work unless you've added the right conda channels. Specify what these channels should be. With only `defaults` and `conda-forge` channels, `conda` will be unable to find packages:

```bash
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - zstd==1.5.5=hc292b87_0
  - zstandard==0.22.0=pypi_0
  - zlib==1.2.13=h5eee18b_0
  - ...
```

**Comment by JasonGross** [comment]
Is `transformer_lens` even on any conda channel?  [Search](https://anaconda.org/search?q=transformer_lens) [suggests](https://anaconda.org/search?q=transformer-lens) not, and I don't see `conda` anywhere in the repo, so I'd close this as "won't fix".  The correct commands for installing with `pip` are given in the README.

**Comment by JoshEngels** [comment]
Yeah before I had some stuff about conda which was incorrect, pip is the supported package manager now
